### ISSUE TITLE
EZR-USB Pinout

### ISSUE THREAD

**Issue by drasko** [MOSAIC-LoPoW/dash7-ap-open-source-stack#48]
Can somebody please give the sketch (image) of EZR-USB pinout, as pins are not marked on PCB?

**Comment by maartenweyn** [comment]
Hi Drasko,

Thanks for noticing

I updated the schematic and uploaded the documentation on github : https://github.com/MOSAIC-LoPoW/dash7-ap-open-source-stack/tree/master/hardware/EZR32-USB

Maarten
