### ISSUE TITLE
Regression of gateway / sensor_push demo in 7bcf4a7

### ISSUE THREAD

**Issue by maximevince** [MOSAIC-LoPoW/dash7-ap-open-source-stack#62]
Since 7bcf4a7de83d785ad161caa712edf784c05c51e9,
I cannot receive frames sent by sensor_push anymore.
Reverting just that commit, fixes the issue for me.
I am using two B-L072Z-LRWAN1 boards with Murata sx1276 radios.

**Comment by glennergeerts** [comment]
confirmed, thanks for reporting!

**Comment by glennergeerts** [comment]
fixed in b58e5c4 , please retry

**Comment by glennergeerts** [comment]
should be resolved, so closing
