### ISSUE TITLE
assertion fail in configure_next_event()

### ISSUE THREAD

**Issue by meishaoming** [MOSAIC-LoPoW/dash7-ap-open-source-stack#66]
Hi, 

I encounter a asser fail while doing some test, sensor_pull on B-L072Z-LRWAN1 platform.

Below is the last lines log:

> [3866] [PHY] READ FIFO 59
[3867] 1E 11 AE 46 32 30 39 00 2C 00 30 20 01 42 37 34 34 00 3B 00 44 88 C2 00 5D 01 40 00 02 7B B6
[3868] [PHY] RX done (0 dBm)
[3869] [DLL] guard channel
[3870] [DLL] packet received @ 147557 , RSSI = 0
[3871] [NONE] Packet queue mark received 0x20001688, slot 0assertion "((int32_t)fire_delay) > 0" failed: file "/Users/sam/dash7-ap-open-source-stack/stack/framework/components/timer/timer.c", line 301, function: configure_next_event

Then i check the source, it is in file `timer.c` function `configure_next_event()`:

```c
#ifndef NDEBUG	    
			//check that we didn't try to schedule a timer in the past
			//normally this shouldn't happen but it IS theoretically possible...
      fire_delay = (next_fire_time - timer_get_counter_value() - timer_info->min_delay_ticks);
			//fire_delay should be in [0,COUNTER_OVERFLOW_INCREASE]. if this is not the case, it is because timer_get_counter() is
			//now larger than next_fire_event, which means we 'missed' the event
			assert(((int32_t)fire_delay) > 0);
#endif 
```

<img width="739" alt="image" src="https://user-images.githubusercontent.com/22272994/49693955-a88bf200-fbbb-11e8-8113-d1f26cc3aa0b.png">

If the LPTIM counter increase 1 between two pieces of code framed by red line in the picture, the assert will failed. right?

I change the code below and test it no assert failed here again. 

```c
#ifndef NDEBUG	    
			//check that we didn't try to schedule a timer in the past
			//normally this shouldn't happen but it IS theoretically possible...
      fire_delay = (next_fire_time - timer_get_counter_value() - timer_info->min_delay_ticks) + 1;
			//fire_delay should be in [0,COUNTER_OVERFLOW_INCREASE]. if this is not the case, it is because timer_get_counter() is
			//now larger than next_fire_event, which means we 'missed' the event
			assert(((int32_t)fire_delay) > 0);
#endif
```

I don't know if this modification is correct, I hope I can discuss it with you.

**Comment by meishaoming** [comment]
sorry, this assert fail appeared again after this modification. 

i am doing more test and debug on it.

**Comment by meishaoming** [comment]
add a log, and reproduce the assert fail.

```c
#ifndef NDEBUG
			//check that we didn't try to schedule a timer in the past
			//normally this shouldn't happen but it IS theoretically possible...
            fire_delay = (next_fire_time - timer_get_counter_value() - timer_info->min_delay_ticks) + 1;
			//fire_delay should be in [0,COUNTER_OVERFLOW_INCREASE]. if this is not the case, it is because timer_get_counter() is
			//now larger than next_fire_event, which means we 'missed' the event
            if (((int32_t)fire_delay) <= 0) {
                log_print_stack_string(LOG_STACK_FWK, "fire_delay %u, next_fire_time %u, counter_value %u, min_delay_ticks %u",
                                       fire_delay, next_fire_time, timer_get_counter_value(),timer_info->min_delay_ticks );
            }
			assert(((int32_t)fire_delay) > 0);
#endif
```

log:

> [237097] [PHY] Switching to sleep mode
[237098] [PHY] resuming from sleep mode
[237099] [PHY] sync_word = f498, ch_coding 2
[237100] [PHY] Switching to sleep mode
[237101] [PHY] resuming from sleep mode
[237102] [PHY] sync_word = f498, ch_coding 2
[237103] [PHY] Switching to sleep mode
[237104] [PHY] resuming from sleep mode
[237105] [PHY] sync_word = f498, ch_coding 2
[237106] [PHY] Switching to sleep mode
[237107] [NONE] fire_delay 0, next_fire_time 6575904, counter_value 6575900, min_delay_ticks 5assertion "((int32_t)fire_delay) > 0" failed: file "/Users/sam/dash7-ap-open-source-stack/stack/framework/components/timer/timer.c", line 306, function: configure_next_event

**Comment by glennergeerts** [comment]
ok thanks for the detailed information, I see the problem indeed. I did not notice it myself, probably because I'm not using debug builds for longer running tests, so this code is removed by precompiler. The modification you propose looks fine, can you create a PR please?

Related to this: we will probably re-add support for a normal timer next to LPTIMER as well, since for some internal timings the delay of setting the LPTIMER is too big

**Comment by meishaoming** [comment]
Thanks for your reply. i make a [PR](https://github.com/MOSAIC-LoPoW/dash7-ap-open-source-stack/pull/69) for it. Please check if this is as your expectation.

**Comment by glennergeerts** [comment]
ok, merged. I will close this for now
