### ISSUE TITLE
Can this project be used on Linux?

### ISSUE THREAD

**Issue by busyluo** [MOSAIC-LoPoW/dash7-ap-open-source-stack#73]
Or is there a plan?

**Comment by glennergeerts** [comment]
The stack needs real-time support which afaik cannot be garantueed when running on top of a normal Linux kernel. Maybe it is possible on a real-time variant or in kernelspace, I don't know. What we normally do is integrate a serial modem with a Linux system, where the modem module contains one MCU on which the stack runs.

Or do you mean using Linux as a development environment?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by busyluo** [comment]
Thank you very much for your reply,  you have solved my question.
