### ISSUE TITLE
Potentially too many EEPROM bytes occupied by the metadata section (file headers)

### ISSUE THREAD

**Issue by abkaya** [MOSAIC-LoPoW/dash7-ap-open-source-stack#87]
The metadata section occupies 3068 bytes, as seen below:
```
section                               size         addr
.d7ap_fs_metadata_section            0xbfc    0x8080000
```
This results from (`dash7-ap-open-source-stack > stack > fs > d7ap_fs_data.c`) :
```c
__attribute__((used)) uint8_t d7ap_fs_metadata[4 + 4 + (255 * 12)] LINKER_SECTION_FS_METADATA = {...
```

Since the header type used is only 9 bytes (`#define FS_FILE_HEADER_SIZE sizeof(fs_file_t)`), I don't think it's necessary to claim 12 bytes per header in the metadata section:
```c
typedef struct __attribute__((__packed__))
{
    uint8_t blockdevice_index; // the members of fs_blockdevice_types_t are required, but more blockdevices can be registered in the futute
    uint32_t length;
    uint32_t addr;
} fs_file_t;
```

I believe the size is confused with `sizeof(d7ap_fs_file_header_t)`, which is equal to 12 and corresponds to the header size for the header defined in the ALP spec `Table 5.1.6.1: File Header`.

So we could limit the allocated bytes in the metadata by changing the line above in `d7ap_fs_data.c` to:
```c
__attribute__((used)) uint8_t d7ap_fs_metadata[4 + 4 + (256 * 9)] LINKER_SECTION_FS_METADATA = {...
```

I also changed the 255 to 256, which probably was a mistake that went unnoticed due to the overhead introduced by the 12 bytes per header allocation.

Doing so frees 756 EEPROM bytes, which is likely a welcome change for a scarce resource.

All of the above can of course be ignored (except the 255 -> 256 change) if the 12 byte allocation per system file header is RFU.

What are your thoughts on this? Is this is a warranted change? If so, can I send in a pull request?

**Comment by glennergeerts** [comment]
Seems correct, this will idd be a remainder from when we were still using `d7ap_fs_file_header_t`. Good catch! A PR would be appreciated, thanks already!
